### ISSUE TITLE
当Item获取焦点时，焦点框因为层级问题会被遮挡。

### ISSUE THREAD

**Issue by musicyy** [songwenju/CustomTvRecyclerView#1]
![device-2016-12-28-150047](https://cloud.githubusercontent.com/assets/3365289/21515915/99a2c652-cd0e-11e6-97cb-8d8e88d65d7f.png)
如图

**Comment by songwenju** [comment]
嗯嗯，你的系统Android版本是多少？

**Comment by musicyy** [comment]
4.4.2的版本，你那里没有这个问题吗？是什么版本的系统？

**Comment by songwenju** [comment]
5.1的系统，周一来了之后我做一下兼容

**Comment by songwenju** [comment]
该问题已经解决了
